### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by NoahCardoza** [bmg02/randominfo#2]
```
Traceback (most recent call last):
  File "/Users/vulcan/projects/vanished.io/backend/data/data-gen.py", line 31, in <module>
    print(randominfo.get_email(randominfo.Person()))
  File "/Users/vulcan/.pyenv/versions/3.9.0/lib/python3.9/site-packages/randominfo/__init__.py", line 297, in __init__
    self.address = get_address()
  File "/Users/vulcan/.pyenv/versions/3.9.0/lib/python3.9/site-packages/randominfo/__init__.py", line 267, in get_address
    if addr[i] != '':
IndexError: list index out of range
```

Thought I'd give this project a try but no luck.. I'm on Mac running Python 3.9.

**Comment by AlfonsoCuesta** [comment]
Same... Mac running Python 3.8. 
As far as I have seen, the bug is in the get_address () function, it extracts the addresses of a csv with 10 columns, although from the code it tries to access up to 12.

**Comment by Adwaith-Rajesh** [comment]
Same issue here, running windows python 3.9

**Comment by Adwaith-Rajesh** [comment]
> Same... Mac running Python 3.8.
> As far as I have seen, the bug is in the get_address () function, it extracts the addresses of a csv with 10 columns, although from the code it tries to access up to 12.

I tried adding a if statement that prevents the "error prone if statement" from checking if 'i' is below a certain number but another list index out of range error occurs some where else.

**Comment by AlfonsoCuesta** [comment]
I think the problem is in the data.csv, the function is taken in order each value, but in the csv the values are in the wrong position. There must be missing fields in the csv or something like this, because if you change the range for I you will get something but in wrong positions and null elements.

**Comment by puroong** [comment]
```python3
def get_address():
	full_addr = []
	addrParam = ['street', 'landmark', 'area', 'city', 'state', 'country', 'pincode']
	for i in range(5,12):
		addrFile = csv.reader(open(full_path('data.csv'), 'r'))
		allAddrs = []
		for addr in addrFile:
			if addr[i] != '':
				allAddrs.append(addr[i])
		full_addr.append(choice(allAddrs))
	full_addr = dict(zip(addrParam, full_addr))
	return full_addr
```

![iTcEOYxzmQ4m](https://user-images.githubusercontent.com/15786615/114996715-0f332000-9eda-11eb-86d2-39dd280a0480.png)

it seems range is set to 5~12 while csv has only 10 columns

**Comment by puroong** [comment]
is address supposed be one of `street address`, `landmark`, `area`, `city`, `state`?

**Comment by alex-pancho** [comment]
```
def get_address():
	full_addr = []
	addrParam = ['street', 'landmark', 'area', 'city', 'state', 'country', 'pincode']
	for i in range(5,12):
		addrFile = csv.reader(open(full_path('data.csv'), 'r'))
		allAddrs = []
		for addr in addrFile:
			if addr != '':
				allAddrs.append(addr)
		full_addr.append(choice(allAddrs))
	full_addr = dict(zip(addrParam, full_addr))
	return full_addr
```

**Comment by alex-pancho** [comment]
fix a lot of error in fork: https://github.com/alex-pancho/randominfo

**Comment by lucasschn** [comment]
@alex-pancho Is your fork available on pip? If not, why not opening a PR here?

**Comment by lucasschn** [comment]
@alex-pancho Thanks for fixing it! Is your fork available on pip? If not, why not opening a PR here?

**Comment by lucasschn** [comment]
I tried with `pip install rndinfo`, but I couldn't find any distribution there
